import { StyleSheet } from "react-native";

export const styles = StyleSheet.create(
    {
      scrollContainer:{
        height:'100%'
      },
      firstSection:{
        marginBottom:174,
        alignContent:'center'
      },
      secondSection:{
        width:'100%',
        marginBottom:24,
        marginLeft:'8%'
      },
      title:{
        textAlign:'left',
        fontSize:20,
        lineHeight:28,
        marginLeft:24,
        marginTop:8,
        color:'#1DA1F2',
        fontWeight:'bold'
      }
    }
  );
  
  export const loginStyle = StyleSheet.create(
    {
    firstSection:{
        height:'100%',
        backgroundColor:'#141d26'
      },
    secondSection:{
        marginLeft:32,
        marginBottom:32
    },
    thirdSection:{
        alignItems:'center',
        justifyContent:'center'
    },
    loginLogo:{
        marginBottom:16,
        width:128,
        height:128,
    },
    title:{
        color:'#1DA1F2',
        fontSize:30,
        lineHeight:36,
        fontWeight:'bold',
        marginBottom:32
    },
    fourthSection:{
      backgroundColor:'#1B2630',
      width:256,
      height:64,
      justifyContent:'center',
      borderWidth:1,
      borderColor:'#1DA1F2',
      borderRadius:30,
      marginBottom:16
    },
    loginInputs:{
      marginLeft:24,
      marginTop:16,
      color:'#1DA1F2'
    },
    fifthSection:{
      backgroundColor:'#1B2630',
      width:256,
      height:64,
      justifyContent:'center',
      borderWidth:1,
      borderRadius:30,
      borderColor:'#1DA1F2'
    },
    sideText:{
      color:'#1DA1F2',
      fontSize:14,
      marginLeft:128,
      marginTop:8,
      marginBottom:24
    },
    sixthSection:{
      backgroundColor:'#1DA1F2',
      width:256,
      height:64,
      alignItems:'center',
      justifyContent:'center',
      borderRadius:30
    },
    loginText:{
      color:'#141d26',
      textAlign:'center',
      fontSize:24,
      lineHeight:32,
      fontWeight:'bold'
    }
  }
  );
  